{% set name = "duckargs" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eriknyquist/duckargs/archive/v{{ version }}.tar.gz
  sha256: 0af01e868fe21ca31384f970fc241d6714fe4196a2448a977c6d0b8506bc78ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  source_files:
    - tests
  imports:
    - duckargs
  commands:
    - pip check
    # Skip test_readme_example it fails upstream too
    - pytest -vvv --capture=tee-sys -k "not test_readme_example" tests
  requires:
    - pip
    - pytest

about:
  home: http://github.com/eriknyquist/duckargs
  license: Apache-2.0
  license_file: LICENSE
  summary: Productivity tool for quickly creating python programs that parse command-line arguments.

extra:
  recipe-maintainers:
    - thewchan
