{% set name = "duckargs" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eriknyquist/duckargs/archive/v{{ version }}.tar.gz
  sha256: 5e8bee146cf095d1931e145e74926a4b85d5fdf063f2555418ac92b0886f5e68

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - duckargs
  commands:
    - pip check
    # Skip test_readme_example it fails upstream too
    - pytest -vvv --capture=tee-sys -k "not test_readme_example" tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: http://github.com/eriknyquist/duckargs
  license: Apache-2.0
  license_file: LICENSE
  summary: Productivity tool for quickly creating python programs that parse command-line arguments.

extra:
  recipe-maintainers:
    - thewchan
